Repository C3-Zally/api-python, pull requests merged in 2020-08, with the labels that each got.

#7 Create django.yml
  .github/workflows/django.yml
Labels: CI, enhancement, help wanted

#8 ADD Complements
  .github/workflows/django.yml
Labels: enhancement

#9 view reports api modified, making tests
  recoverid/cares/migrations/0001_initial.py
  recoverid/cares/views.py
  recoverid/cities/migrations/0001_initial.py
  recoverid/countries/migrations/0001_initial.py
  recoverid/countries/urls.py
  recoverid/reports/migrations/0001_initial.py
  recoverid/reports/models/reports.py
  recoverid/reports/views.py
  recoverid/states/migrations/0001_initial.py
Labels: bug, enhancement

#10 ADD Features - ft-miguel
  .editorconfig
  .gitignore
  LICENSE
  README.md
Labels: CI, documentation, enhancement

#11 ADD New Features
  .editorconfig
  .gitignore
  LICENSE
  README.md
Labels: CI, bug, documentation, enhancement

#12 Ft antonio
  db.sqlite3
  recoverid/cares/migrations/0001_initial.py
  recoverid/cares/views.py
  recoverid/cities/migrations/0001_initial.py
  recoverid/countries/migrations/0001_initial.py
  recoverid/countries/views.py
  recoverid/reports/migrations/0001_initial.py
  recoverid/reports/models/reports.py
  recoverid/reports/urls.py
  recoverid/reports/views.py
  recoverid/settings.py
  recoverid/states/migrations/0001_initial.py
  requirements.txt
Labels: bug, duplicate

#13 ADD - Features
  db.sqlite3
  recoverid/cares/views.py
  recoverid/countries/views.py
  recoverid/reports/urls.py
  recoverid/reports/views.py
  recoverid/settings.py
  requirements.txt
Labels: CI, enhancement

#15 Ft antonio
  recoverid/cares/views.py
  recoverid/countries/views.py
  recoverid/reports/urls.py
  recoverid/reports/views.py
Labels: CI, bug, documentation, duplicate, enhancement

#16 Features
  recoverid/cares/views.py
  recoverid/countries/views.py
  recoverid/reports/apps.py
  recoverid/reports/models/reports.py
  recoverid/reports/urls.py
  recoverid/reports/views.py
  recoverid/settings.py
  recoverid/states/apps.py
  recoverid/states/models/states.py
  recoverid/states/views.py
  recoverid/urls.py
  recoverid/utils/models.py
Labels: CI, documentation, duplicate, enhancement
